### ISSUE TITLE
Error 400: invalid_request

### ISSUE THREAD

**Issue by HsnVahedi** [mahieyin-rahmun/NextJsWithDRFExample#5]
Hi, just tried cloning this repo and run the application. Got this error from google after clicking to sign in with google:
`Error 400: invalid_request`

![Screenshot from 2021-05-18 12-29-07](https://user-images.githubusercontent.com/13330853/118627925-c9b58b80-b7d4-11eb-8048-bf5e445975db.png)

Any advice?

**Comment by mahieyin-rahmun** [comment]
Did you add the `client_id` and `client_secret` in your .env.local file?

Follow the file [here](https://github.com/mahieyin-rahmun/NextJsWithDRFExample/blob/main/client/.env.example) and setup a .env.local file in the `client` directory.

**Comment by HsnVahedi** [comment]
Yes, I did @mahieyin-rahmun

**Comment by mahieyin-rahmun** [comment]
That's odd. Could you check that:

1. In the .env.local file, the `client_id` is not surrounded by quotation marks, has no spaces in between and starts right after the = operator? e.g. GOOGLE_CLIENT_ID=xYz
2. You are referring to the correct key that is specified in the .env file in the `[...nextauth].ts` file? 
3. Your .env file is being loaded by Next.js?
